implements HINTERNET
AdrianCassar/xenia-canary pull request #36
Opened 2024-06-18 19:52 UTC by wildmaster84

2024-06-19 07:14 UTC, Gliniak requested changes

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  std::string rawUrl;
std::string rawUrl = fmt::format("{}:{}", server_name, port);

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  if (this->type() != HINTERNET::Type::Session) {
There should never be a case that object has types, especially for such constructs.

I suppose there must be another type, but I guess ignore it for now

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +    return 1;
Why 1? If it is incorrect it should be 0

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  // int isConencted = hConnection->Connect(hConnection->handle());
Remove unused code

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +uint32_t HINTERNET::SendRequest(std::string Header, std::string data,
You're returning only false/true from it. It should be bool instead of uint32_t

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +    return FALSE;
use false instead of FALSE.

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +      return TRUE;
use true instead of TRUE.

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  return FALSE;
use false instead of FALSE.

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +uint32_t HINTERNET::Connect() {
Same thing as in method above + same TRUE->true, FALSE->false

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  if (curl) {
Reverse this condition. Aka.
if (!curl) {
  return false;
}

<remaining code>

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +    curl_easy_cleanup(curl);
unreachable code. Previous check matches all posible conditions

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +    if (result != CURLE_OK) {
Protip: first do cleanup then just: `return result == CURLE_OK`

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.h
> +using namespace std::chrono_literals;
You're not even using literals here. Remove

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.h
> +#include <algorithm>
Remove unused includes. 
I suspect: algo, atomic and cstddef is unused

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +HINTERNET* hInternet;
global pointer? We don't do that here, but I understand kinda why you did it that way

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  if (dwUrlLength < 1) {
just `if (!dwUrlLength)`

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  if (hostname.length() < 1) {
hostname.empty()?

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  if (hConnect <= 1) {
You can aggregate both conditions into one.

`if (!hConnect || !hInternet)`

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  XELOGI("HttpCloseHandle: {}", handle);
It's printed anyway, so no need for double printing

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  if (handle == 1) {
Same thing, you can aggregate there conditions into one

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/xam/xam_net.cc
> +  return NULL;
Do not return null from calls that return dword_result_t, It's better to return 0 or even better some X_STATUS code

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> + * Copyright 2013 Ben Vanik. All rights reserved.                             *
2013->2024

2024-06-19 07:14 UTC, Gliniak commented on src/xenia/kernel/hinternet.cc
> +  return this->handle();
just handle(). There is no need to explicitly use this->

2024-09-15 08:21 UTC, craftycodie commented on src/xenia/kernel/xam/xam_net.cc
> +  strncpy(service_endpoint, cvars::api_address.c_str(), service_endpoint_len);
Could you explain what this "service_endpoint" is used for? It being set to the API address suggests to me that changes to the API are also needed.

2024-09-18 07:14 UTC, wildmaster84 commented
fixed

2024-09-19 00:33 UTC, wildmaster84 commented
I feel like something with this commit is off so please take a look at it. when looking at curl the path logged to console is ":80" but seems to work fine. Minecraft connects to a test server just fine and initial connect in the menus does not cause a crash.

2025-03-25 03:26 UTC, wildmaster84 commented
needs alot more work

2025-03-25 03:26 UTC, closed without merging